### ISSUE TITLE
Could not find file 'C:\Users\HP\navdb.csv'

### ISSUE THREAD

**Issue by Yhubee** [JannesMeyer/z.ps#2]
@JannesMeyer 

![no-navdbcsv](https://cloud.githubusercontent.com/assets/22277667/18958187/b8745ac4-8659-11e6-8e7a-44c55625de27.jpg)

**Comment by JannesMeyer** [comment]
Hi,

I'm still using this project myself, so it should still be working, even
though there haven't been any recent commits.

That file is where it stores the recently used folder locations.

Maybe your user doesn't have write access to your home directory? That
sounds a bit peculiar though.

Jannes

**Comment by Yhubee** [comment]
> Maybe your user doesn't have write access to your home directory?

I don't follow

**Comment by JannesMeyer** [comment]
Don't worry. It's probably something else anyway.

Would you mind running this command in a PowerShell terminal and showing me the output?

```
Import-Csv "$env:UserProfile\navdb.csv" -Encoding 'Unicode'
```

Also it would be helpful to know which version of PowerShell/Windows you are running. You should be able to find out your PowerShell version by running this command:

```
$PSVersionTable
```

**Comment by Yhubee** [comment]
I can't do the import command because I started using [(https://github.com/vincpa/z)]

It's PS Version 5.1.14393.206 though
